In [46]:
import pandas as pd
import numpy as np

In [47]:
data = pd.read_csv("car_price_dataset.csv")

## Data Analysis

In [48]:
data.head(3)

,Unnamed: 0,Brand,Model,YOM,Engine (cc),Gear,Fuel Type,Millage(KM),Town,Date,Leasing,Condition,AIR CONDITION,POWER STEERING,POWER MIRROR,POWER WINDOW,Price
0,0,AUDI,A1,2016,990.0,Automatic,Petrol,99000.0,Gampaha,2025-02-05,No Leasing,USED,Available,Available,Available,Available,100.0
1,1,AUDI,A1,2017,1000.0,Automatic,Petrol,88000.0,Colombo,2025-01-14,No Leasing,USED,Available,Available,Available,Available,97.0
2,2,AUDI,A1,2018,1000.0,Automatic,Petrol,77000.0,Dehiwala-Mount-Lavinia,2025-01-23,No Leasing,USED,Available,Available,Available,Available,98.5

In [49]:
data.shape

(9788, 17)

In [50]:
data.isnull().sum()

Unnamed: 0        0
Brand             0
Model             0
YOM               0
Engine (cc)       0
Gear              0
Fuel Type         0
Millage(KM)       0
Town              0
Date              0
Leasing           0
Condition         0
AIR CONDITION     0
POWER STEERING    0
POWER MIRROR      0
POWER WINDOW      0
Price             0
dtype: int64

In [51]:
data.duplicated().sum()

np.int64(0)

In [52]:
data.describe()

        Unnamed: 0          YOM  Engine (cc)    Millage(KM)        Price
count  9788.000000  9788.000000  9788.000000    9788.000000  9788.000000
mean   4893.758991  2006.759093  1260.442358  200649.979567    53.464275
std    2826.028988     9.831574   403.769059  108147.314860    43.625049
min       0.000000  1956.000000   573.000000   11000.000000     2.650000
25%    2446.750000  2001.000000  1000.000000  110000.000000    26.250000
50%    4893.500000  2009.000000  1300.000000  176000.000000    43.000000
75%    7341.250000  2015.000000  1500.000000  264000.000000    69.750000
max    9788.000000  2024.000000  4800.000000  759000.000000   790.000000

In [53]:
data.corr(numeric_only=True)['Price']

Unnamed: 0     0.085756
YOM            0.506669
Engine (cc)    0.193737
Millage(KM)   -0.506669
Price          1.000000
Name: Price, dtype: float64

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9788 entries, 0 to 9787
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      9788 non-null   int64
 1   Brand           9788 non-null   object
 2   Model           9788 non-null   object
 3   YOM             9788 non-null   int64
 4   Engine (cc)     9788 non-null   float64
 5   Gear            9788 non-null   object
 6   Fuel Type       9788 non-null   object
 7   Millage(KM)     9788 non-null   float64
 8   Town            9788 non-null   object
 9   Date            9788 non-null   object
 10  Leasing         9788 non-null   object
 11  Condition       9788 non-null   object
 12  AIR CONDITION   9788 non-null   object
 13  POWER STEERING  9788 non-null   object
 14  POWER MIRROR    9788 non-null   object
 15  POWER WINDOW    9788 non-null   object
 16  Price           9788 non-null   float64
dtypes: float64(3), int64(2), object(12)
memory usage: 1.3+ MB

In [55]:
data.head(2)

,Unnamed: 0,Brand,Model,YOM,Engine (cc),Gear,Fuel Type,Millage(KM),Town,Date,Leasing,Condition,AIR CONDITION,POWER STEERING,POWER MIRROR,POWER WINDOW,Price
0,0,AUDI,A1,2016,990.0,Automatic,Petrol,99000.0,Gampaha,2025-02-05,No Leasing,USED,Available,Available,Available,Available,100.0
1,1,AUDI,A1,2017,1000.0,Automatic,Petrol,88000.0,Colombo,2025-01-14,No Leasing,USED,Available,Available,Available,Available,97.0

In [56]:
data['Brand'].value_counts()

Brand
TOYOTA           3089
SUZUKI           2473
NISSAN           1248
HONDA             681
MITSUBISHI        284
PERODUA           257
MICRO             244
HYUNDAI           189
MAZDA             181
MERCEDES-BENZ     168
TATA              115
KIA               113
DAIHATSU           88
BMW                80
RENAULT            58
AUDI               56
PEUGEOT            55
CHERY              44
FORD               43
CHEVROLET          38
PROTON             29
ISUZU              28
ZOTYE              28
MINI               24
FIAT               23
DATSUN             21
AUSTIN             17
VOLVO              17
SUBARU             16
DAEWOO             16
VOLKSWAGEN         15
OPEL                8
BAJAJ               6
JAGUAR              6
MORRIS              5
LEXUS               3
MG                  3
FOTON               3
TESLA               2
WILLYS              2
SKODA               2
MAHINDRA            2
JAC                 1
CITROEN             1
BYD                 1
LAND-ROVER          1
JONWAY              1
JEEP                1
SEAT                1
OTHER               1
Name: count, dtype: int64

In [57]:
len(data['Brand'].value_counts())

50

In [58]:
data['Brand'] = data['Brand'].apply(
    lambda x: x if data['Brand'].value_counts()[x] >= 100 else 'OTHERS'
)

In [59]:
data['Brand'].value_counts()

Brand
TOYOTA           3089
SUZUKI           2473
NISSAN           1248
OTHERS            746
HONDA             681
MITSUBISHI        284
PERODUA           257
MICRO             244
HYUNDAI           189
MAZDA             181
MERCEDES-BENZ     168
TATA              115
KIA               113
Name: count, dtype: int64

In [60]:
data['Brand'].unique()

array(['OTHERS', 'HONDA', 'HYUNDAI', 'KIA', 'MAZDA', 'MERCEDES-BENZ',
       'MICRO', 'MITSUBISHI', 'NISSAN', 'PERODUA', 'SUZUKI', 'TATA',
       'TOYOTA'], dtype=object)

In [61]:
data['Model'].value_counts()

Model
ALTO                 392
VITZ                 366
WAGON R STINGRAY     282
MARUTI               229
WAGON R              204
                    ...
POLO GT                1
PASSAT B5.5 TURBO      1
A6 TFSI                1
A6 T1.8                1
A4 RS4 CONVERSION      1
Name: count, Length: 1555, dtype: int64

In [62]:
len(data['Model'].value_counts())

1555

In [63]:
data['YOM'].unique()

array([2016, 2017, 2018, 2015, 2001, 2010, 2019, 2011, 2012, 1999, 2003,
       2014, 2013, 2004, 2024, 1960, 1998, 1980, 1969, 1997, 1995, 1970,
       1961, 1990, 2000, 2007, 2006, 2005, 1974, 1988, 1993, 1991, 2002,
       2020, 2009, 2008, 1996, 1987, 1994, 1986, 1989, 1985, 1982, 1972,
       1979, 1977, 1992, 1984, 2021, 1962, 2022, 1978, 1975, 2023, 1967,
       1965, 1968, 1983, 1981, 1959, 1976, 1956])

In [64]:
data['Engine (cc)'].unique()

array([ 990. , 1000. , 1500. , 1750. ,  999. , 1899. , 1900. , 1800. ,
       1400. , 2000. , 1600. , 3000. , 1300. , 1275. , 1499. , 1990. ,
       1997. , 1995. , 2200. , 1590. , 1796. , 2500. , 1980. ,  650. ,
       2990. , 4400. , 1200. ,  800. ,  812. ,  798. ,  670. ,  833. ,
        900. , 1100. , 1320. , 1330. , 1319. , 1198. , 1234. , 2198. ,
       1568. , 1113. , 1290. ,  660. ,  850. ,  825. ,  847. ,  890. ,
        680. , 1170. , 1171. ,  799. ,  813. , 1366. , 1240. , 1299. ,
       2139. , 1598. , 1490. , 2400. , 1498. , 1322. , 1495. , 1450. ,
       1799. , 1350. , 1339. , 1422. , 1470. , 1390. , 1328. , 1360. ,
       1496. , 1399. , 1550. , 1493. , 1893. , 1488. , 2003. , 1333. ,
        690. ,  658. , 1714. , 1341. , 1562. , 1395. , 1599. , 1790. ,
        814. ,  815. , 1197. , 2180. , 1566. , 1086. , 1970. , 1999. ,
       2100. , 1794. , 1533. , 1480. , 2190. , 2800. , 1950. , 1998. ,
        998. ,  946. , 1343. , 2468. , 1080. , 1542. , 1324. , 1274. ,
       1340. , 1680. , 1373. , 1597. , 1608. , 1650. , 1587. , 1497. ,
       2144. , 1332. , 2150. , 2596. , 1979. , 3200. , 3750. , 3500. ,
       1987. , 1988. , 2600. , 1584. , 1580. ,  997. , 1143. , 1342. ,
       1278. , 1075. ,  970. , 2680. , 2476. , 1460. , 1879. , 2470. ,
       1410. , 1822. , 1298. , 1250. , 1456. , 1300.8, 1780. , 1270. ,
       1190. , 1700. , 1830. , 1760. , 1890. , 1843. , 1989. , 1973. ,
       2350. , 2340. , 2300. , 1534. , 1295. , 1707. ,  980. ,  993. ,
       1740. , 1115. , 1016. , 1719. , 1785. , 1527. , 1850. , 1428. ,
       1397. , 1611. , 2184. , 1388. ,  989. , 2950. , 1411. , 1468. ,
        880. , 2016. ,  796. ,  790. , 1060. , 1111. ,  698. ,  640. ,
        860. ,  669. ,  600. ,  746. ,  964. , 1097. , 1008. ,  996. ,
        984. ,  695. , 1329. ,  795. ,  909. ,  630. ,  718. , 1242. ,
        768. , 1061. ,  659. ,  700. , 1063. , 1005. ,  657. ,  651. ,
        665. ,  620. ,  750. , 1193. , 1396. , 1405. , 1180. , 1398. ,
       2448. ,  624. ,  625. ,  626. ,  629. ,  610. ,  645. ,  634. ,
        573. , 1536. , 1870. , 1512. , 1483. , 1820. , 1660. , 1842. ,
       1297. , 2362. , 2360. , 1920. , 1974. , 1618. , 1735. , 1667. ,
       1809. , 1280. , 1975. , 1930. , 1679. , 1773. , 1589. , 1960. ,
       1032. , 1420. , 1720. , 1452. , 1898. , 1347. , 2970. , 2480. ,
       2164. , 1362. , 4800. , 1514. , 1716. , 1789. , 1283. , 1077. ,
       1015. , 1276. , 1896. , 2770. , 1948. , 1798. ])

In [65]:
data['Gear'].value_counts()

Gear
Automatic    6305
Manual       3483
Name: count, dtype: int64

In [66]:
data['Millage(KM)'].value_counts()

Millage(KM)
110000.0    836
88000.0     612
198000.0    558
99000.0     549
77000.0     530
           ...
638000.0      2
660000.0      2
627000.0      1
726000.0      1
759000.0      1
Name: count, Length: 62, dtype: int64

In [67]:
data.head(2)

,Unnamed: 0,Brand,Model,YOM,Engine (cc),Gear,Fuel Type,Millage(KM),Town,Date,Leasing,Condition,AIR CONDITION,POWER STEERING,POWER MIRROR,POWER WINDOW,Price
0,0,OTHERS,A1,2016,990.0,Automatic,Petrol,99000.0,Gampaha,2025-02-05,No Leasing,USED,Available,Available,Available,Available,100.0
1,1,OTHERS,A1,2017,1000.0,Automatic,Petrol,88000.0,Colombo,2025-01-14,No Leasing,USED,Available,Available,Available,Available,97.0

## Removing Unwanted Columns

In [68]:
data = data.drop(['Unnamed: 0','Date', 'Town', 'Model'], axis=1)

In [69]:
data.head(2)

,Brand,YOM,Engine (cc),Gear,Fuel Type,Millage(KM),Leasing,Condition,AIR CONDITION,POWER STEERING,POWER MIRROR,POWER WINDOW,Price
0,OTHERS,2016,990.0,Automatic,Petrol,99000.0,No Leasing,USED,Available,Available,Available,Available,100.0
1,OTHERS,2017,1000.0,Automatic,Petrol,88000.0,No Leasing,USED,Available,Available,Available,Available,97.0

In [70]:
data.shape

(9788, 13)

## One-Hot Encoding

In [71]:
data = pd.get_dummies(data)

In [72]:
data.shape

(9788, 35)

In [73]:
data.head(2)

,YOM,Engine (cc),Millage(KM),Price,Brand_HONDA,Brand_HYUNDAI,Brand_KIA,Brand_MAZDA,Brand_MERCEDES-BENZ,Brand_MICRO,...,Condition_NEW,Condition_USED,AIR CONDITION_Available,AIR CONDITION_Not_Available,POWER STEERING_Available,POWER STEERING_Not_Available,POWER MIRROR_Available,POWER MIRROR_Not_Available,POWER WINDOW_Available,POWER WINDOW_Not_Available
0,2016,990.0,99000.0,100.0,False,False,False,False,False,False,...,False,True,True,False,True,False,True,False,True,False
1,2017,1000.0,88000.0,97.0,False,False,False,False,False,False,...,False,True,True,False,True,False,True,False,True,False

In [74]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9788 entries, 0 to 9787
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   YOM                           9788 non-null   int64
 1   Engine (cc)                   9788 non-null   float64
 2   Millage(KM)                   9788 non-null   float64
 3   Price                         9788 non-null   float64
 4   Brand_HONDA                   9788 non-null   bool
 5   Brand_HYUNDAI                 9788 non-null   bool
 6   Brand_KIA                     9788 non-null   bool
 7   Brand_MAZDA                   9788 non-null   bool
 8   Brand_MERCEDES-BENZ           9788 non-null   bool
 9   Brand_MICRO                   9788 non-null   bool
 10  Brand_MITSUBISHI              9788 non-null   bool
 11  Brand_NISSAN                  9788 non-null   bool
 12  Brand_OTHERS                  9788 non-null   bool
 13  Brand_PERODUA                 9788 non-null   bool
 14  Brand_SUZUKI                  9788 non-null   bool
 15  Brand_TATA                    9788 non-null   bool
 16  Brand_TOYOTA                  9788 non-null   bool
 17  Gear_Automatic                9788 non-null   bool
 18  Gear_Manual                   9788 non-null   bool
 19  Fuel Type_Diesel              9788 non-null   bool
 20  Fuel Type_Electric            9788 non-null   bool
 21  Fuel Type_Hybrid              9788 non-null   bool
 22  Fuel Type_Petrol              9788 non-null   bool
 23  Leasing_No Leasing            9788 non-null   bool
 24  Leasing_Ongoing Lease         9788 non-null   bool
 25  Condition_NEW                 9788 non-null   bool
 26  Condition_USED                9788 non-null   bool
 27  AIR CONDITION_Available       9788 non-null   bool
 28  AIR CONDITION_Not_Available   9788 non-null   bool
 29  POWER STEERING_Available      9788 non-null   bool
 30  POWER STEERING_Not_Available  9788 non-null   bool
 31  POWER MIRROR_Available        9788 non-null   bool
 32  POWER MIRROR_Not_Available    9788 non-null   bool
 33  POWER WINDOW_Available        9788 non-null   bool
 34  POWER WINDOW_Not_Available    9788 non-null   bool
dtypes: bool(31), float64(3), int64(1)
memory usage: 602.3 KB

In [75]:
print(data.columns)

Index(['YOM', 'Engine (cc)', 'Millage(KM)', 'Price', 'Brand_HONDA',
       'Brand_HYUNDAI', 'Brand_KIA', 'Brand_MAZDA', 'Brand_MERCEDES-BENZ',
       'Brand_MICRO', 'Brand_MITSUBISHI', 'Brand_NISSAN', 'Brand_OTHERS',
       'Brand_PERODUA', 'Brand_SUZUKI', 'Brand_TATA', 'Brand_TOYOTA',
       'Gear_Automatic', 'Gear_Manual', 'Fuel Type_Diesel',
       'Fuel Type_Electric', 'Fuel Type_Hybrid', 'Fuel Type_Petrol',
       'Leasing_No Leasing', 'Leasing_Ongoing Lease', 'Condition_NEW',
       'Condition_USED', 'AIR CONDITION_Available',
       'AIR CONDITION_Not_Available', 'POWER STEERING_Available',
       'POWER STEERING_Not_Available', 'POWER MIRROR_Available',
       'POWER MIRROR_Not_Available', 'POWER WINDOW_Available',
       'POWER WINDOW_Not_Available'],
      dtype='object')

## Seperate Features and Target

In [76]:
x = data.drop('Price', axis=1)
y = data['Price']

## Train Test Split

In [83]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [84]:
x_train.shape, x_test.shape

((7341, 34), (2447, 34))

## Model Training

In [85]:
def model_acc(model):
    model.fit(x_train, y_train)
    acc = model.score(x_test, y_test)
    print(str(model)+ " --> " +str(acc))

In [87]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model_acc(lr)

from sklearn.linear_model import Lasso
lasso = Lasso()
model_acc(lasso)

from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
model_acc(dt)

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
model_acc(rf)

LinearRegression() --> 0.6089450802937997
Lasso() --> 0.5217843185076767
DecisionTreeRegressor() --> 0.8642013438431243
RandomForestRegressor() --> 0.8814396022130093

In [88]:
from sklearn.model_selection import GridSearchCV

parameters = {'n_estimators':[10, 50, 100],
             'criterion':['squared_error', 'absolute_error', 'poisson']}

grid_obj = GridSearchCV(estimator=rf, param_grid=parameters)

grid_fit = grid_obj.fit(x_train, y_train)

best_model = grid_fit.best_estimator_
best_model

RandomForestRegressor(criterion='poisson')

In [89]:
best_model.score(x_test,y_test)

0.8843386573491415

## Saving as a pickle file

In [40]:
import pickle
with open('predictor.pickle', 'wb') as file:
    pickle.dump(best_model, file)

In [90]:
x_train.columns

Index(['YOM', 'Engine (cc)', 'Millage(KM)', 'Brand_HONDA', 'Brand_HYUNDAI',
       'Brand_KIA', 'Brand_MAZDA', 'Brand_MERCEDES-BENZ', 'Brand_MICRO',
       'Brand_MITSUBISHI', 'Brand_NISSAN', 'Brand_OTHERS', 'Brand_PERODUA',
       'Brand_SUZUKI', 'Brand_TATA', 'Brand_TOYOTA', 'Gear_Automatic',
       'Gear_Manual', 'Fuel Type_Diesel', 'Fuel Type_Electric',
       'Fuel Type_Hybrid', 'Fuel Type_Petrol', 'Leasing_No Leasing',
       'Leasing_Ongoing Lease', 'Condition_NEW', 'Condition_USED',
       'AIR CONDITION_Available', 'AIR CONDITION_Not_Available',
       'POWER STEERING_Available', 'POWER STEERING_Not_Available',
       'POWER MIRROR_Available', 'POWER MIRROR_Not_Available',
       'POWER WINDOW_Available', 'POWER WINDOW_Not_Available'],
      dtype='object')

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9788 entries, 0 to 9787
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   YOM                           9788 non-null   int64
 1   Engine (cc)                   9788 non-null   float64
 2   Millage(KM)                   9788 non-null   float64
 3   Price                         9788 non-null   float64
 4   Brand_HONDA                   9788 non-null   bool
 5   Brand_HYUNDAI                 9788 non-null   bool
 6   Brand_KIA                     9788 non-null   bool
 7   Brand_MAZDA                   9788 non-null   bool
 8   Brand_MERCEDES-BENZ           9788 non-null   bool
 9   Brand_MICRO                   9788 non-null   bool
 10  Brand_MITSUBISHI              9788 non-null   bool
 11  Brand_NISSAN                  9788 non-null   bool
 12  Brand_OTHERS                  9788 non-null   bool
 13  Brand_PERODUA                 9788 non-null   bool
 14  Brand_SUZUKI                  9788 non-null   bool
 15  Brand_TATA                    9788 non-null   bool
 16  Brand_TOYOTA                  9788 non-null   bool
 17  Gear_Automatic                9788 non-null   bool
 18  Gear_Manual                   9788 non-null   bool
 19  Fuel Type_Diesel              9788 non-null   bool
 20  Fuel Type_Electric            9788 non-null   bool
 21  Fuel Type_Hybrid              9788 non-null   bool
 22  Fuel Type_Petrol              9788 non-null   bool
 23  Leasing_No Leasing            9788 non-null   bool
 24  Leasing_Ongoing Lease         9788 non-null   bool
 25  Condition_NEW                 9788 non-null   bool
 26  Condition_USED                9788 non-null   bool
 27  AIR CONDITION_Available       9788 non-null   bool
 28  AIR CONDITION_Not_Available   9788 non-null   bool
 29  POWER STEERING_Available      9788 non-null   bool
 30  POWER STEERING_Not_Available  9788 non-null   bool
 31  POWER MIRROR_Available        9788 non-null   bool
 32  POWER MIRROR_Not_Available    9788 non-null   bool
 33  POWER WINDOW_Available        9788 non-null   bool
 34  POWER WINDOW_Not_Available    9788 non-null   bool
dtypes: bool(31), float64(3), int64(1)
memory usage: 602.3 KB